services:
  db:
    image: mongo:latest
    container_name: menti-mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: menti-redis
    restart: unless-stopped
    ports:
      - "6380:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: menti-api
    env_file:
      - .env
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/${MONGO_INITDB_DATABASE}?authSource=admin
      REDIS_URI: redis://redis:6379
      BETTER_AUTH_URL: http://host.docker.internal:8000
    depends_on:
      - db
      - redis
    ports:
      - "4080:3000"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: menti-worker
    command: ["npm", "run", "worker"]
    env_file:
      - .env
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/${MONGO_INITDB_DATABASE}?authSource=admin
      REDIS_URI: redis://redis:6379
      BETTER_AUTH_URL: http://host.docker.internal:8000
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  db_data:
