name: Deploy Menti
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Create .env
              run: |
                  echo "${{ secrets.ENV }}" > .env

            - name: Upload .env
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  source: ".env"
                  target: "/home/${{ secrets.SSH_USER }}/projects/mentimeter"

            - name: Deploy
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      cd ~/projects/mentimeter
                      git fetch origin
                      git reset --hard origin/main
                      sudo docker compose down
                      sudo docker compose build --no-cache
                      sudo docker compose up -d
                      sudo docker image prune -af
